### PR TITLE
Migrate to GTK3

### PR DESCRIPTION
**Pull request by invidian**
Includes commits from #64, which could hopefully be merged before this PR.

GKT2 interface:
Selection_182

GTK3:
Selection_183

### CODE REVIEW

**Comment by aramg** [comment]
Taking a quick look, seems good, so thanks for this. 
I'll review closer and try compiling myself when I get some extra time.

RE libjpeg-turbo: unfortunately its not packaged properly and consistently across distros. 
eg. on Ubuntu, its a bit of a mess. There are "turbojpeg"s and "libjpeg-turbo"s on top of the regular libjpeg. Static linking guarantees the client is using the correct lib with all the optimizations and removes a confusing dependency from the install instructions.

**Comment by invidian** [comment]
Thanks for quick and positive reply @aramg. I'm not expert with C, but things seems to work with this patches.

I removed the patch for shared library. I also found that it contained some code changes which resolved pointer-to-int-cast warnings, so I put them into separate commit and put them here.

To test with shared `libturbojpeg`, you can run `make JPEG_DIR="" JPEG_INCLUDE="" JPEG_LIB="" JPEG=$(pkg-config --libs --cflags libturbojpeg)`.

**Comment by invidian** [comment]
Resolved conflicts after recent updates.

**Comment by invidian** [comment]
Thanks!

**Pull request merged**
