### PR TITLE
Build fix for Fedora 31

### PR DESCRIPTION
**Pull request by GabVenturato**
This is based on the pull requests from @pdvrieze. I hope I've done things properly, forking the main repository, and merging his changes.

Some problems still were present, which didn'tt let me build. Moreover, I preferred to create the build inside the proper subfolder `build`.

I've had to change some parameters to let it be compliant with the newer version of ffmpeg. Plus, a function from libjpeg-turbo was preventing me to compile. The function which I am talking about is `jpeg_src_mem_tj`. Actually I couldn't find very consistent information neither online, nor in the library documentation. However, changing the function to `jpeg_src_mem`, which actually has the same parameters and it is documented, solved the problem.

### CODE REVIEW

**Comment by pdvrieze** [comment]
I checked it in the source code, both are identical. You may have seen that I have two requests. On my system both are needed (the cmake stuff so that clion works, the other one to fix the issues)

**Comment by aramg** [comment]
Hi, do you mind trying this branch: https://github.com/aramg/droidcam/tree/upgrades
(see readme for libjpeg-turbo link)

**Comment by GabVenturato** [comment]
@pdvrieze oh sorry, I thought the most recent one included the fix. In fact I didn't understand how you managed to compile! 

However, maybe my work is not all lost time: in Fedora the cmake couldn't find the swscale library, I've had to change the CMakeLists in order to let it find the path.

Maybe is it better if I close this pull request and add another one with just that change?

Sorry again, it's the first time I try to collaborate with pull requests!

@aramg I will try it today, I will let you know.

**Comment by aramg** [comment]
Closing this, please try latest master, and new patches still welcome.

**Pull request closed without merging**
