### PR TITLE
Added AppIndicator widget 

### PR DESCRIPTION
**Pull request by eazel7**
I added an AppIndicator widget to my build.
what would be a better way to determine the icon path?

image

### CODE REVIEW

**Comment by aramg** [comment]
Thanks, I'll review this when I get a chance.
Also not sure, the icon is built into the executable to avoid that decision.

**Review by doamatto — APPROVED** [review]
Looks good to me

**Comment by aramg** [comment]
A modified version of this is now in https://github.com/aramg/droidcam/commits/ver15
Please comment if you'd like, I would like to release v1.5 tomorrow.

**Comment by doamatto** [comment]
That sounds solid too

**Pull request closed without merging**
