### PR TITLE
Rotation option

### LINKED ISSUE #38: Missing rotation/flipping options
Investigate using avfilter.

https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/filtering_video.c
http://ffmpeg.org/ffmpeg-filters.html

### PR DESCRIPTION
**Pull request by BernardoGO**
This feature is present in the Windows version but missing in the Linux client.
It is using TurboJpeg to perform a fast transform that rotates the image.

It should resolve #38 and #36.

### CODE REVIEW

**Comment by aramg** [comment]
Thanks. I'll see if I can review and test it out this week.

**Comment by aramg** [comment]
Gave it a quick test, this is what I get at 90

Screen Shot 2020-09-16 at 4 30 45 PM

**Comment by aramg** [comment]
Only applying tjTransform works better but its not centred and needs special handling if the input resolution doesn't match the webcam.

Screen Shot 2020-09-16 at 4 58 40 PM

**Comment by BernardoGO** [comment]
It is not possible to use only the tjTransform. The rest is supposed to fix the resolution.

I've just tested it again and was not able to replicate the issue you are having. Can you give me more information on the configuration you are using?

image

**Comment by BernardoGO** [comment]
Try using:
`sudo insmod /lib/modules/`uname -r`/kernel/drivers/media/video/v4l2loopback-dc.ko width=480 height=640`

**Comment by aramg** [comment]
> Try using:
> `sudo insmod /lib/modules/`uname -r`/kernel/drivers/media/video/v4l2loopback-dc.ko width=480 height=640`

Right, then it might work.
But I'm not sure how that would translate to user experience and if all programs will load the webcam with the inverted options. 
Ideally the webcam will stay loaded as-is and the image is transformed into the 640x480 area.

Maybe if the app starts using generic v4l2loopback, there can be 2 different devices, vertical & horizontal one

**Comment by BernardoGO** [comment]
I've just tried with the default value for the insmod and it works fine.
It doesn't seem to be the issue then.

Are you using the default values? 640x480?

**Comment by BernardoGO** [comment]
Did you load it through the GUI or CLI?

**Comment by aramg** [comment]
Compiled the code as-is. Using GUI client, the input is a 640x480 image.

```
$ git log -1
commit a660e539eef68d9f9f3c425267312fa1aca5549a (HEAD -> pr100, upstream/master)
Author: BernardoGO <bernardo.godinho.oliveira@gmail.com>
Date:   Wed Sep 16 13:30:48 2020 -0300
```

Tried opening device in VLC and also with ffplay, same result.
```
$ ffplay /dev/video0 
Input #0, video4linux2,v4l2, from '/dev/video0':B sq=    0B f=0/0   
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 640x480

**Comment by aramg** [comment]
It works with the inverted webcam (480x640), but then 0º and 180º are messed up.

**Comment by aramg** [comment]
Lets see if anyone else tries and gives some feedback.
I think have an idea on how to make this work in a somewhat user-friendly way.

**Comment by BernardoGO** [comment]
Yes, I'll try to figure that out as well.
Can you create a development branch, aside from master, for us to commit to it?

That way we can merge this PR and work on the solution together without breaking master.

**Comment by aramg** [comment]
I pushed some edits to https://github.com/aramg/droidcam/tree/pr100
A little busy right now with the apps, but I'll come back to this soon.
If the inverted webcam works in popular programs, this approach seems good.

**Comment by aramg** [comment]
Pushed some code to auto-detect inverted webcam and transform the video.
By loading the webcam in portrait orientation then it should be possible to get portrait video, and visa-versa.

**Comment by BernardoGO** [comment]
Is it compiling as is?

It throws an error for me:

> 
> src/decoder.c: In function ‘int decoder_prepare_video(char*)’:
> src/decoder.c:244:45: error: ‘struct jpg_dec_ctx_s’ has no member named ‘dstSlice’; did you mean ‘tjDstSlice’?
>   244 |     jpg_decoder.tjDstSlice[1] = jpg_decoder.dstSlice[0] + jpg_decoder.m_ySize;
>       |                                             ^~~~~~~~
>       |                                             tjDstSlice
> src/decoder.c:245:45: error: ‘struct jpg_dec_ctx_s’ has no member named ‘dstSlice’; did you mean ‘tjDstSlice’?
>   245 |     jpg_decoder.tjDstSlice[2] = jpg_decoder.dstSlice[1] + jpg_decoder.m_uvSize;
>       |                                             ^~~~~~~~
>       |                                             tjDstSlice
> src/decoder.c: In function ‘void process_frame(JPGFrame*)’:
> src/decoder.c:297:25: error: ‘tjHandle’ was not declared in this scope; did you mean ‘tjhandle’?
>   297 |         if (tjTransform(tjHandle, p, len, 1, &p, &len, &jpg_decoder.transform, 0)) {
>       |                         ^~~~~~~~
>       |                         tjhandle
> src/decoder.c: In function ‘void decoder_horizontal_flip()’:
> src/decoder.c:405:22: error: ‘struct jpg_dec_ctx_s’ has no member named ‘transfer’; did you mean ‘transform’?
>   405 |     if ((jpg_decoder.transfer.op & TJXOP_HFLIP) == 0) {
>       |                      ^~~~~~~~
>       |                      transform
> src/decoder.c:406:21: error: ‘struct jpg_dec_ctx_s’ has no member named ‘transfer’; did you mean ‘transform’?
>   406 |         jpg_decoder.transfer.op |= TJXOP_HFLIP;
>       |                     ^~~~~~~~
>       |                     transform
> src/decoder.c:409:21: error: ‘struct jpg_dec_ctx_s’ has no member named ‘transfer’; did you mean ‘transform’?
>   409 |         jpg_decoder.transfer.op &= (~TJXOP_HFLIP);
>       |                     ^~~~~~~~
>       |                     transform
> make: *** [Makefile:38: droidcam-cli] Error 1
> 
>

**Comment by aramg** [comment]
I didnt try compiling yet, just wrote the code on my Mac. There might be some simple typos.

It'd be interesting to test different programs with the vertical webcam, mot popular ones have to work for this to get released. Skype, Discord, OBS, Zoom, ???

**Comment by aramg** [comment]
Cleaned up and got it working. https://github.com/aramg/droidcam/commits/ver15
I think it's ready to be released.

**Comment by logerom** [comment]
Hi, is the rotation feature released for the linux client? I cant find it.

**Comment by p2lab** [comment]
> Hi, is the rotation feature released for the linux client? I cant find it.

Wondering the same thing

**Comment by aramg** [comment]
Rotation is supported by inverting the webcam (see bottom of "HD Mode" at https://www.dev47apps.com/droidcam/linux/).
It's also possible to use OBS Studio + DroidCam OBS, which essentially turns OBS Studio into the "client".
A new cross-platform client for droidcam is one of the upcoming milestones.

**Pull request closed without merging**
