### PR TITLE
Create a CMake build file

### PR DESCRIPTION
**Pull request by pdvrieze**
This depends on #22 as without those fixes the system cannot be built with shared libraries. A CMake file to make it possible to work on the code in CMake

### CODE REVIEW

**Comment by aramg** [comment]
Hi, could I get some feedback on the latest Makefile?
For such a small project, I feel it should just work and no need for cmake

**Comment by morsik** [comment]
@aramg just send you PR for fixing latest Makefile.

I agree that CMake is overkill here.

**Comment by pdvrieze** [comment]
The reason I made it was because it is needed for CLion

**Comment by morsik** [comment]
Kinda stupid reason… it's your specific IDE.
Also: https://plugins.jetbrains.com/plugin/9333-makefile-support

**Pull request closed without merging**
